import './integration-loader.mjs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {writeFileSync} from 'node:fs';
// Fail closed: this runner only writes to the dedicated disposable database.
const url = new URL(process.env.DATABASE_URL || '');
assert.equal(url.hostname,'127.0.0.1'); assert.equal(url.port,'55439');
process.env.AUTH_JWT_SECRET = randomUUID()+randomUUID();
process.env.SUPABASE_URL=''; process.env.SUPABASE_JWT_SECRET='';
const {NextRequest}=await import('next/server');
const {prisma}=await import('../../../../lib/server/prisma.ts');
const {signAppAccessToken}=await import('../../../../lib/server/app-jwt.ts');
const clubs=await import('../../../../app/api/v1/clubs/route.ts');
const clubDetail=await import('../../../../app/api/v1/clubs/[id]/route.ts');
const invites=await import('../../../../app/api/v1/clubs/[id]/invite/route.ts');
const redeem=await import('../../../../app/api/v1/clubs/join-by-code/route.ts');
const mine=await import('../../../../app/api/v1/me/sessions/route.ts');
const outings=await import('../../../../app/api/v1/sessions/route.ts');
const detail=await import('../../../../app/api/v1/sessions/[id]/route.ts');
const join=await import('../../../../app/api/v1/sessions/[id]/join/route.ts');
const leave=await import('../../../../app/api/v1/sessions/[id]/leave/route.ts');
const participants=await import('../../../../app/api/v1/sessions/[id]/participants/route.ts');
const assign=await import('../../../../app/api/v1/sessions/[id]/assign/route.ts');
const complete=await import('../../../../app/api/v1/sessions/[id]/complete/route.ts');
const inbox=await import('../../../../app/api/v1/me/inbox/route.ts');
const approve=await import('../../../../app/api/v1/clubs/[id]/approve/route.ts');
const clubLeave=await import('../../../../app/api/v1/clubs/[id]/leave/route.ts');
const requestClub=await import('../../../../app/api/v1/clubs/[id]/request/route.ts');
const resolveClub=await import('../../../../app/api/v1/clubs/resolve/route.ts');
const legacyJoin=await import('../../../../app/api/v1/clubs/join/route.ts');
const roster=await import('../../../../app/api/v1/clubs/[id]/roster/route.ts');
const run=randomUUID(); const host=`host-${run}`, guest=`guest-${run}`, stranger=`stranger-${run}`;
const tokens={}; for(const id of [host,guest,stranger]) tokens[id]=await signAppAccessToken(id);
async function call(handler,{user,body,id,query=''}={}) {
 const headers={}; if(user) headers.authorization=`Bearer ${tokens[user]}`;
 if(body!==undefined) headers['content-type']='application/json';
 const req=new NextRequest(`http://localhost/api/v1/test${query}`,{method:body===undefined?'GET':'POST',headers,...(body===undefined?{}:{body:JSON.stringify(body)})});
 const response=await handler(req,{params:Promise.resolve({id})});
 return {status:response.status,...await response.json()};
}
function ok(result){assert.equal(result.status,200,JSON.stringify(result));return result.data;}
let checks=0;function pass(name){checks++;console.log(`PASS ${name}`);}
try {
 assert.equal((await call(clubs.POST,{body:{name:'Photo'}})).status,401);
 assert.equal((await call(clubs.POST,{user:host,body:{name:'  '}})).status,400);
 const a=ok(await call(clubs.POST,{user:host,body:{name:'Photo libre',city:'Rabat',description:'Observer ensemble',visibility:'public',joinMode:'open'}}));
 const b=ok(await call(clubs.POST,{user:host,body:{name:'Photo libre',city:'Rabat',description:'Un groupe privé',visibility:'members'}}));
 assert.notEqual(a.id,b.id);assert.notEqual(a.slug,b.slug);
 assert.equal(await prisma.clubMembership.count({where:{userId:host,role:'admin',status:'approved'}}),2);
 pass('two independently persisted clubs, generated slugs, atomic admin membership, invalid/anonymous creation');
 assert.equal((await call(clubDetail.GET,{id:b.id})).status,404);
 assert.equal((await call(invites.POST,{user:stranger,id:b.id,body:{}})).status,403);
 assert.equal((await call(invites.POST,{user:host,id:b.id,body:{expiresInDays:-1}})).status,400);
 const invitation=ok(await call(invites.POST,{user:host,id:b.id,body:{}}));
 assert.equal(invitation.code.length,32);assert.ok(invitation.expiresAt);
 const accepted=ok(await call(redeem.POST,{user:guest,body:{code:` ${invitation.code.toLowerCase()} `}}));
 const retried=ok(await call(redeem.POST,{user:guest,body:{code:invitation.code}}));assert.equal(accepted.membership.id,retried.membership.id);
 assert.equal((await call(clubDetail.GET,{user:guest,id:b.id})).status,200);
 pass('private club protection, authorized invitation issuance, redemption and retry');
 await prisma.clubMembership.update({where:{id:accepted.membership.id},data:{status:'banned'}});
 assert.equal((await call(redeem.POST,{user:guest,body:{code:invitation.code}})).status,403);
 await prisma.clubMembership.update({where:{id:accepted.membership.id},data:{status:'pending'}});
 ok(await call(redeem.POST,{user:guest,body:{code:invitation.code}}));
 await prisma.clubInvite.update({where:{id:invitation.id},data:{expiresAt:new Date(0)}});
 assert.equal((await call(redeem.POST,{user:stranger,body:{code:invitation.code}})).status,410);
 pass('banned membership cannot be restored by code; pending membership approved; expired invite rejected');
 const draft={title:'Observer la ville',meetingPoint:'Rabat, entrée du parc',hostName:'Hôte test',programme:'Marcher et photographier',dateISO:new Date(Date.now()+86400000).toISOString(),experience:{kind:'community',activity:'walk',format:'open',durationMinutes:45}};
 const first=ok(await call(outings.POST,{user:host,body:{...draft,clubId:a.id}}));
 const second=ok(await call(outings.POST,{user:host,body:{...draft,title:'Conversation espagnole',clubId:a.id,experience:{...draft.experience,format:'language',language:'Espagnol',level:'Débutant'}}}));
 const hidden=ok(await call(outings.POST,{user:host,body:{...draft,clubId:b.id,visibility:'public'}}));
 const standalone=ok(await call(outings.POST,{user:host,body:draft}));
 assert.equal(standalone.clubId,null);assert.equal(hidden.visibility,'members');
 assert.equal(second.experience.language,'Espagnol');assert.equal(first.experience.language,undefined);
 assert.equal(new Set([first.id,second.id,hidden.id,standalone.id]).size,4);
 assert.equal((await call(outings.POST,{user:stranger,body:{...draft,clubId:b.id}})).status,403);
 assert.equal((await call(outings.POST,{user:host,body:{...draft,dateISO:'2026-02-30'}})).status,400);
 assert.equal((await call(outings.POST,{user:host,body:{...draft,dateISO:new Date(0).toISOString()}})).status,400);
 assert.equal((await call(outings.POST,{user:host,body:{...draft,experience:{...draft.experience,format:'language'}}})).status,400);
 pass('four persisted outings; club association, standalone, language-specific data, inherited privacy and input checks');
 // Deliberately emulate an old inconsistent record to exercise the relational query.
 await prisma.session.update({where:{id:hidden.id},data:{visibility:'public'}});
 const listing=ok(await call(outings.GET,{query:`?clubId=${b.id}`}));assert.equal(listing.sessions.length,0);
 assert.equal((await call(detail.GET,{id:hidden.id})).status,404);
 assert.equal((await call(join.POST,{user:stranger,id:hidden.id,body:{}})).status,404);
 assert.equal((await call(detail.GET,{user:guest,id:hidden.id})).status,200);
 pass('actual PostgreSQL visibility filtering denies private legacy records and guessed ids');
 const joined=await Promise.all([1,2,3].map(()=>call(join.POST,{user:guest,id:first.id,body:{}})));
 joined.forEach(ok);assert.equal(await prisma.sessionAttendance.count({where:{sessionId:first.id,userId:guest}}),1);
 ok(await call(join.POST,{user:guest,id:second.id,body:{}}));
 ok(await call(leave.POST,{user:guest,id:first.id,body:{}}));
 ok(await call(leave.POST,{user:guest,id:first.id,body:{}}));
 assert.equal((await prisma.sessionAttendance.findUnique({where:{sessionId_userId:{sessionId:second.id,userId:guest}}})).status,'joined');
 assert.equal((await prisma.sessionAttendance.findUnique({where:{sessionId_userId:{sessionId:first.id,userId:guest}}})).status,'left');
 assert.equal((await call(leave.POST,{user:stranger,id:first.id,body:{}})).status,404);
 const myOutings=ok(await call(mine.GET,{user:guest})).sessions;
 assert.ok(myOutings.some(s=>s.id===second.id && s.experience.language==='Espagnol' && s.attendanceStatus==='joined'));
 assert.ok(!myOutings.some(s=>s.id===first.id));
 pass('concurrent join retry creates one row; selected cancellation is repeatable and preserves other outing');
 const publicClubs=ok(await call(clubs.GET)).clubs;
 assert.ok(publicClubs.some(c=>c.id===a.id));assert.ok(!publicClubs.some(c=>c.id===b.id));
 pass('public club discovery excludes private clubs; personal outings preserve title, language and participation');
 assert.equal((await call(participants.GET,{id:hidden.id})).status,404);
 assert.equal((await call(participants.GET,{user:stranger,id:hidden.id})).status,404);
 assert.equal((await call(participants.GET,{user:guest,id:hidden.id})).status,200);
 await prisma.sessionAttendance.create({data:{sessionId:hidden.id,userId:stranger,status:'suggested'}});
 assert.ok(!ok(await call(inbox.GET,{user:stranger})).sessionNotifications.some(n=>n.sessionId===hidden.id));
 await prisma.sessionAttendance.update({where:{sessionId_userId:{sessionId:hidden.id,userId:stranger}},data:{status:'joined'}});
 assert.equal((await call(complete.POST,{user:stranger,id:hidden.id,body:{}})).status,404);
 pass('participants, inbox and completion respect relational privacy, including stale attendance');
 assert.equal((await call(assign.POST,{user:stranger,id:standalone.id,body:{userId:guest,groupId:'community'}})).status,403);
 assert.equal((await call(assign.POST,{user:host,id:standalone.id,body:{userId:guest,groupId:'A'}})).status,400);
 ok(await call(assign.POST,{user:host,id:standalone.id,body:{userId:guest,groupId:'community'}}));
 await prisma.sessionAttendance.update({where:{sessionId_userId:{sessionId:standalone.id,userId:guest}},data:{status:'attended'}});
 assert.equal(ok(await call(assign.POST,{user:host,id:standalone.id,body:{userId:guest,groupId:'community'}})).status,'attended');
 assert.equal((await call(assign.POST,{user:host,id:hidden.id,body:{userId:stranger,groupId:'community'}})).status,404);
 pass('standalone assignment requires its host; club assignment requires an approved target member');
 const other=ok(await call(clubs.POST,{user:stranger,body:{name:'Other administrator',visibility:'public',joinMode:'approval'}}));
 const pending=ok(await call(requestClub.POST,{user:guest,id:other.id,body:{}}));
 assert.equal(pending.status,'pending');
 assert.equal((await call(approve.POST,{user:host,id:a.id,body:{membershipId:pending.id}})).status,404);
 assert.equal((await prisma.clubMembership.findUnique({where:{id:pending.id}})).status,'pending');
 ok(await call(approve.POST,{user:stranger,id:other.id,body:{membershipId:pending.id}}));
 ok(await call(approve.POST,{user:stranger,id:other.id,body:{membershipId:pending.id}}));
 pass('approval is scoped to the administrator club and safe to retry');
 assert.equal((await call(resolveClub.POST,{body:{slug:b.slug}})).status,404);
 assert.equal((await call(resolveClub.POST,{user:guest,body:{slug:b.slug}})).status,200);
 assert.equal((await call(resolveClub.POST,{body:{inviteCode:invitation.code}})).status,410);
 assert.equal((await call(requestClub.POST,{user:stranger,id:b.id,body:{}})).status,404);
 assert.equal((await call(requestClub.POST,{user:stranger,id:a.id,body:{}})).data.status,'approved');
 pass('private slug and expired invitation resolution are protected; public open-club request joins correctly');
 const freshInvite=ok(await call(invites.POST,{user:host,id:b.id,body:{}}));
 const legacyAccepted=ok(await call(legacyJoin.POST,{user:stranger,body:{code:freshInvite.code.toLowerCase()}}));
 ok(await call(legacyJoin.POST,{user:stranger,body:{code:freshInvite.code}}));
 await prisma.clubMembership.update({where:{id:legacyAccepted.membership.id},data:{status:'banned'}});
 assert.equal((await call(legacyJoin.POST,{user:stranger,body:{code:freshInvite.code}})).status,403);
 assert.equal((await call(clubLeave.POST,{user:stranger,id:b.id,body:{}})).status,403);
 await prisma.clubInvite.update({where:{id:freshInvite.id},data:{invitedEmail:'fixture@example.invalid'}});
 assert.equal((await call(resolveClub.POST,{body:{inviteCode:freshInvite.code}})).status,403);
 assert.equal((await call(legacyJoin.POST,{user:guest,body:{code:freshInvite.code}})).status,403);
 pass('legacy invitation endpoint shares contact, ban and retry rules; leaving cannot erase a ban');
 await prisma.clubMembership.update({where:{id:accepted.membership.id},data:{sharePrs:false,prSummary:{records:[{label:'private fixture',paceSecondsPerKm:300}]}}});
 const members=ok(await call(roster.GET,{user:host,id:b.id})).members;
 assert.equal(members.find(m=>m.userId===guest).prSummary,null);
 assert.equal((await call(roster.GET,{user:guest,id:b.id})).status,403);
 assert.equal((await call(clubLeave.POST,{user:host,id:b.id,body:{}})).status,409);
 await prisma.clubMembership.create({data:{clubId:a.id,userId:guest,role:'admin',status:'approved'}});
 const leaving=await Promise.all([host,guest].map(user=>call(clubLeave.POST,{user,id:a.id,body:{}})));
 assert.ok(leaving.some(x=>x.status===200));assert.ok(leaving.some(x=>x.status===409));
 assert.equal(await prisma.clubMembership.count({where:{clubId:a.id,role:'admin',status:'approved'}}),1);
 pass('PR sharing choice honored; concurrent administrator departures cannot orphan a club');
 await prisma.$disconnect();
 const persisted=await prisma.session.findUnique({where:{id:second.id}});assert.equal(persisted.experience.language,'Espagnol');
 writeFileSync('/tmp/grpd-d02-persistence.json',JSON.stringify({outingId:second.id,clubIds:[a.id,b.id],host,guest}));
 pass('disconnect/reconnect retains clubs, outings and structured language data');
 console.log(`${checks} integration groups passed using actual route handlers, signed JWTs and PostgreSQL. No deployment claimed.`);
} finally {await prisma.$disconnect();}
